channel_sources:
  - msys2, conda-forge, defaults    # [win]
  - conda-forge, defaults           # [not win]
channel_targets:
  - tudat-team main
c_compiler:       # [win]
  - clang         # [win]
cxx_compiler:     # [win]
  - clang         # [win]