{% set name = "cspice-cmake" %}

package:
  name: "{{ name }}"
  version: 66.0

source:
  git_rev: 132bebde844c263ae1b5b287f96fb6e2b21580ce
  git_url: https://github.com/tudat-team/cspice-cmake.git

build:
  number: 1
  ignore_run_exports:
    - m2w64-gcc-libs  # [win]

requirements:
    build:
        - cmake
        - {{ compiler('c') }}               # [not win]
        - {{ compiler('m2w64_c') }}         # [win]
#        - vs2017_{{ target_platform  }}     # [win]

#        - m2w64-gcc                         # [win]
#        - m2-patch                         # [win]
#        - vs2017_{{ target_platform  }}    # [win]

about:
  home: https://github.com/tudat-team/cspice-cmake
  license: BSD
  license_family: BSD
  summary: Mirror of SPICE Toolbox sourcecode with additional CMake files for building along the tudatBundle.
