{% set name = "cspice-cmake" %}

package:
  name: "{{ name }}"
  version: 66

source:
  git_rev: 6bac73966c90d3af2abde24145d7c4d66acf837f
  git_url: https://github.com/tudat-team/cspice-cmake.git

build:
  number: 2

requirements:
    build:
        - cmake
        - {{ compiler('c') }}

about:
  home: https://github.com/tudat-team/cspice-cmake
  license: BSD
  license_family: BSD
  summary: Mirror of SPICE Toolbox sourcecode with additional CMake files for building along the tudatBundle.
