{% set name = "cspice-cmake" %}

package:
  name: "{{ name }}"
  version: 67

source:
  git_rev: 4f1a62b354277ac8e363834c9af5fb32f88ddd11
  git_url: https://github.com/tudat-team/cspice-cmake.git

build:
  number: 0

requirements:
    build:
        - cmake
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - make    # [unix]

about:
  home: https://github.com/tudat-team/cspice-cmake
  license: BSD
  license_family: BSD
  summary: Mirror of SPICE Toolbox sourcecode with additional CMake files.
