{% set name = "cspice-cmake" %}

package:
  name: "{{ name }}"
  version: 66.0

source:
  git_rev: ea828646e1e42fe381f3f7ed368f8b7574d4742d
  git_url: https://github.com/tudat-team/cspice-cmake.git

build:
  number: 1

requirements:
    build:
        - cmake
        - {{ compiler('c') }}

about:
  home: https://github.com/tudat-team/cspice-cmake
  license: BSD
  license_family: BSD
  summary: Mirror of SPICE Toolbox sourcecode with additional CMake files for building along the tudatBundle.
