{ % set name = "cspice-cmake" % }

package:
  name: "{{ name }}"
  version: 66

source:
  git_rev: 6bac73966c90d3af2abde24145d7c4d66acf837f
  git_url: https://github.com/tudat-team/cspice-cmake.git

build:
  number: 2

requirements:
  build:
    - cmake
    - { { compiler('c') } }

about:
  home: https://github.com/tudat-team/cspice-cmake
  license: MIT
  license_family: MIT
  summary: 'NASA ancillary information system built with, and for, CMake'
  description: |
    SPICE is an ancillary information system that provides scientists and
    engineers the capability to include space geometry and event data into
    mission design, science observation planning, and science data analysis
    software.
  doc_url: https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/index.html
  extra:
    recipe-maintainers:
      - ggarrett13
