{% set name = "cspice-cmake" %}

package:
  name: "{{ name }}"
  version: 66.0

source:
  git_rev: b8e665d537ddef5f8b3c829e23268fbc6c5f4655
  git_url: https://github.com/tudat-team/cspice-cmake.git

build:
  number: 1

requirements:
    build:
        - cmake
        - {{ compiler('c') }}

about:
  home: https://github.com/tudat-team/cspice-cmake
  license: BSD
  license_family: BSD
  summary: Mirror of SPICE Toolbox sourcecode with additional CMake files for building along the tudatBundle.
