{% set name = "cspice-cmake" %}

package:
  name: "{{ name }}"
  version: 67

source:
  git_rev: e44da83b8a7a420fdddf02d2e3accebd0ab86e5e
  git_url: https://github.com/tudat-team/cspice-cmake.git

build:
  number: 2

requirements:
    build:
        - cmake
        - {{ compiler('cxx') }}    # [not win]
        - {{ compiler('c') }}      # [not win]
        - {{ compiler('clang') }}  # [win] 
        - make    # [unix]

about:
  home: https://github.com/tudat-team/cspice-cmake
  license: BSD
  license_family: BSD
  summary: Mirror of SPICE Toolbox sourcecode with additional CMake files.
