# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

version: 2

jobs:
  build_linux_64_:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_64_"
      - UPLOAD_PACKAGES: "True"
        DOCKER_IMAGE: "condaforge/linux-anvil-comp7"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: |
            export CI=circle
            export FEEDSTOCK_NAME=$(basename ${CIRCLE_PROJECT_REPONAME})
            ./.scripts/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux_64_
